version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/realestate
    depends_on:
      - php
      - database

  php:
    container_name: php
    build:
      context: ./docker/php/
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www/realestate
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database

  phpmyadmin:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8083:80'
    depends_on:
      - database
      - php
      - nginx